// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq6nq7o1f8kUMa9QxTPtXfR9JCrcF8uJs',
    appId: '1:954473353975:web:ca35a68b7a773e797ef9f2',
    messagingSenderId: '954473353975',
    projectId: 'skybatch-f0755',
    authDomain: 'skybatch-f0755.firebaseapp.com',
    storageBucket: 'skybatch-f0755.appspot.com',
    measurementId: 'G-YECJX57EFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-xMS2L5KOcX0Gg-uLFemnjIcDP7A-UbI',
    appId: '1:954473353975:android:11f07f886b86a9557ef9f2',
    messagingSenderId: '954473353975',
    projectId: 'skybatch-f0755',
    storageBucket: 'skybatch-f0755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYuSRLy_GfpCPdZHLTmR1p_UqMA_0kmc',
    appId: '1:954473353975:ios:ebe6a1bbe08b860a7ef9f2',
    messagingSenderId: '954473353975',
    projectId: 'skybatch-f0755',
    storageBucket: 'skybatch-f0755.appspot.com',
    iosBundleId: 'com.example.skybatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYuSRLy_GfpCPdZHLTmR1p_UqMA_0kmc',
    appId: '1:954473353975:ios:045efd107fb9d7af7ef9f2',
    messagingSenderId: '954473353975',
    projectId: 'skybatch-f0755',
    storageBucket: 'skybatch-f0755.appspot.com',
    iosBundleId: 'com.example.skybatch.RunnerTests',
  );
}
